version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      cooldown:
          default-days: 4

    - package-ecosystem: npm
      directory: /docs
      schedule:
          interval: weekly
      cooldown:
          default-days: 4
