# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0
# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
