# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: authorize

permissions: {}

on:
  workflow_call:
    secrets:
      read-org-members:
        description: "Github token with read access to organization members"
        required: true
    inputs:
      github-org:
        description: "Github organization name"
        required: true
        type: string
    outputs:
      result:
        value: ${{ jobs.authorize.outputs.result }}

jobs:
  is-org-member:
    uses: ./.github/workflows/is-org-member.yml
    with:
      github-org: ${{ inputs.github-org }}
      github-user: ${{ github.actor }}
    secrets:
      read-org-members: ${{ secrets.read-org-members }}
  authorize:
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    needs: [is-org-member]
    # Authorization passes without approval if:
    # - The event is not a pull request (e.g. push to main) or
    # - Pull request comes from another branch in the same repo or
    # - Github actor is a member of 'github-org' organization
    # Otherwise, the workflow requires manual approval from a maintainer
    # as configured in the 'external' github environment
    environment: ${{
      ( github.event_name != 'pull_request_target' ||
        github.event.pull_request.head.repo.full_name == github.repository ||
        needs.is-org-member.outputs.is_org_member == 'True' )
      && 'internal' || 'external' }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Set output
        id: set-output
        run: |
          # Valid github environment(s) should set the ENV_DEFINED variable
          # to prevent accidentally running actions in an unset environment:
          if [ -z "$ENV_DEFINED" ]; then
            echo "Running in unexpected environment"
            echo "result=failed" >>"$GITHUB_OUTPUT"
            exit 1
          fi
          echo "Auth OK"
          echo "result=authorized" >>"$GITHUB_OUTPUT"
        env:
          ENV_DEFINED: ${{ vars.ENV_DEFINED }}
