# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: Auto-assign PR author

on:
  # pull_request_target so PRs from forks get a token that can assign; no PR code is checked out.
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  is-org-member:
    if: github.repository == 'tiiuae/ghaf'
    uses: ./.github/workflows/is-org-member.yml
    with:
      github-org: tiiuae
      github-user: ${{ github.event.pull_request.user.login }}
    secrets:
      read-org-members: ${{ secrets.READ_ORG_MEMBERS }}
  auto-assign-pr:
    needs: [is-org-member]
    # Unassigned external PRs stand out.
    if: needs.is-org-member.outputs.is_org_member == 'True'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: pozil/auto-assign-issue@af6beea6bdf1e8eb373f061c5bc168681fc6d011 # v4.0.1
        with:
          abortIfPreviousAssignees: true
          assignees: ${{ github.event.pull_request.user.login }}
