# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: check
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
permissions:
    contents: read

jobs:
    run-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
              with:
                  egress-policy: audit

            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false
            - name: Install nix
              uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
            - name: Check nix flake show runs successfully
              run: nix flake show --all-systems --accept-flake-config
            - name: Check templates
              run: |
                  set -eux -o pipefail
                  tmp_flakes=$(mktemp -d)
                  cleanup() { rm -rf "$tmp_flakes"; }
                  trap cleanup EXIT
                  nix eval --json --apply builtins.attrNames .#templates --accept-flake-config | jq -r '.[]' | while IFS=$'\t' read -r name; do
                    nix flake new -t ".#$name" "${tmp_flakes}/${name}";
                    if [[ "$name" == "ghaf-module" ]]; then
                        nix-instantiate --parse "${tmp_flakes}/${name}/default.nix"
                    else
                       nix flake show "${tmp_flakes}/${name}" --accept-flake-config
                    fi
                  done
