# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: doc
on:
    push:
        branches:
            - main
        paths:
            - "docs/**"
permissions:
    contents: read

jobs:
    deploy:
        name: build doc and deploy to gh pages
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
              with:
                  egress-policy: audit

            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
            - name: build
              run: nix build .#doc --accept-flake-config
            - name: deploy
              uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./result
