# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: doc
on:
    push:
        branches:
            - main
        paths:
            - "docs/**"
permissions:
    contents: read

jobs:
    deploy:
        name: build doc and deploy to gh pages
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
              with:
                  egress-policy: audit

            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false
            - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
            - name: build
              run: nix build .#doc --accept-flake-config
            - name: deploy
              uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./result
