name: nix build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: Run nix build for the selected outputs before merging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            trusted-public-keys = cache.vedenemo.dev:RGHheQnb6rXGK5v9gexJZ8iWTPX6OcSeS56YeXYzOcg= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.vedenemo.dev https://cache.nixos.org/
      - uses: cachix/cachix-action@v12
        with:
          name: cachix-cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#packages.x86_64-linux.generic-x86_64-debug
