# SPDX-FileCopyrightText: 2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: Source VSA

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  source-vsa:
    name: Issue Source VSA
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    concurrency:
      group: source-vsa-${{ github.repository }}-${{ github.sha }}
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Issue Source VSA
        uses: tiiuae/ghaf-infra/.github/actions/source-vsa@e360c480a84c75481f05e9042408a37750aa7447
        with:
          policy: slsa/source-vsa-policy.yaml
          verified-level: SLSA_SOURCE_LEVEL_1
