# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: Handle stale issues and PRs

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      # contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10
        with:
          stale-issue-message: >
            This issue has been open for 30 days with no activity and has been marked as stale.
            Consider updating or closing it if it is no longer relevant.
            Remove the stale label or leave a comment to keep it active.
          stale-pr-message: >
            This PR has been open for 30 days with no activity and has been marked as stale.
            Consider updating or closing it if it is no longer relevant.
            Remove the stale label or leave a comment to keep it active.
          days-before-stale: 30
          days-before-issue-close: -1
          days-before-pr-close: -1
          exempt-issue-labels: "needs-more-info,needs-demo"
          exempt-pr-labels: "pinned,security,do-not-close,Needs Testing"
          operations-per-run: 50 # can be reset to default 30 after a few initial runs
